// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProPayments.Service.Data;

#nullable disable

namespace ProPayments.Service.Migrations
{
    [DbContext(typeof(SubscriptionContext))]
    [Migration("20240823074527_AddColumnTypeTableUserSetting")]
    partial class AddColumnTypeTableUserSetting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("OrderExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<ulong?>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("PaymentAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("TransactionHash")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<ulong>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<ulong>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("PeriodDescription")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductKeyCode")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<int>("ProductOptionPeriod")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<decimal>("ProductOptionPrice")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<ulong?>("ProductRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.LogEntry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("ExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.OrderItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<ulong>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A tool which automates the process of registring in alphabot raffles",
                            Name = "ProRaffle"
                        });
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductKey", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActivated")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<ulong>("OrderItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.HasKey("Code");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ProductOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductKeys");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("PeriodDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 23, 7, 45, 26, 700, DateTimeKind.Utc).AddTicks(6728),
                            Period = 1,
                            PeriodDescription = "1 Month",
                            Price = 12m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 8, 23, 7, 45, 26, 700, DateTimeKind.Utc).AddTicks(6737),
                            Period = 2,
                            PeriodDescription = "2 Months",
                            Price = 20m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 23, 7, 45, 26, 700, DateTimeKind.Utc).AddTicks(6738),
                            Period = 3,
                            PeriodDescription = "3 Months",
                            Price = 30m,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Subscription", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("LastNotificationCheck")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<ulong>("UserSettingId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductOptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Transaction", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("PaymentAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.UserSetting", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProRaffle", b =>
                {
                    b.HasBaseType("ProPayments.Service.Data.Entities.UserSetting");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ProRaffles", (string)null);
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithOne("Invoice")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Invoice", "OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.ProductOption", "ProductOption")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductKey", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.OrderItem", "OrderItem")
                        .WithOne("ProductKey")
                        .HasForeignKey("ProPayments.Service.Data.Entities.ProductKey", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.ProductOption", "ProductOption")
                        .WithMany("ProductKeys")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("ProductKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("ProductOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductOption", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Product", "Product")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Subscription", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.ProductKey", "ProductKey")
                        .WithOne("Subscription")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Subscription", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.ProductOption", "ProductOption")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.UserSetting", "UserSetting")
                        .WithOne("Subscription")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Subscription", "UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductKey");

                    b.Navigation("ProductOption");

                    b.Navigation("User");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Transaction", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Transaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.UserSetting", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProRaffle", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.UserSetting", null)
                        .WithOne()
                        .HasForeignKey("ProPayments.Service.Data.Entities.ProRaffle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.Navigation("Invoice")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.OrderItem", b =>
                {
                    b.Navigation("ProductKey");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Product", b =>
                {
                    b.Navigation("ProductOptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductKey", b =>
                {
                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.ProductOption", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductKeys");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductKeys");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.UserSetting", b =>
                {
                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
