// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProPayments.Service.Data;

#nullable disable

namespace ProPayments.Service.Migrations
{
    [DbContext(typeof(SubscriptionContext))]
    [Migration("20240810214948_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("ProPayments.Service.Data.Entities.AccessCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Code");

                    b.ToTable("AccessCodes");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("OrderExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<ulong?>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("PaymentAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("TransactionHash")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<ulong>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<ulong>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("PeriodDescription")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("PlanOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<int>("PlanOptionPeriod")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<decimal>("PlanOptionPrice")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<ulong?>("PlanRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<ulong?>("SubscriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.LogEntry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("ExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<ulong>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.OrderItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<ulong>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("PlanOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlanOptionId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Experience the essential features of our service with our Free Plan. Ideal for users who want to explore the basic functionalities at no cost. Enjoy a limited duration access and get a glimpse of the premium benefits without any commitment.",
                            Type = "Free"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover the perfect balance with our Basic Plan. Tailored for users who need more than the essentials but aren’t ready for all the premium extras. Enjoy extended access to a range of key features, enhanced support, and additional resources. Ideal for those seeking reliable performance and value.",
                            Type = "Basic"
                        });
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.PlanOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("PeriodDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 8, 10, 21, 49, 48, 346, DateTimeKind.Utc).AddTicks(8287),
                            Period = 3,
                            PeriodDescription = "3 Days",
                            PlanId = 1,
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 8, 10, 21, 49, 48, 346, DateTimeKind.Utc).AddTicks(8292),
                            Period = 1,
                            PeriodDescription = "1 Month",
                            PlanId = 2,
                            Price = 12m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 10, 21, 49, 48, 346, DateTimeKind.Utc).AddTicks(8295),
                            Period = 2,
                            PeriodDescription = "2 Months",
                            PlanId = 2,
                            Price = 20m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 10, 21, 49, 48, 346, DateTimeKind.Utc).AddTicks(8296),
                            Period = 3,
                            PeriodDescription = "3 Months",
                            PlanId = 2,
                            Price = 30m
                        });
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Subscription", b =>
                {
                    b.Property<ulong>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("LastNotificationCheck")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<int>("PlanOptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Transaction", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<ulong>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("PaymentAddress")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithOne("Invoice")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Invoice");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.PlanOption", "PlanOption")
                        .WithMany("OrderItems")
                        .HasForeignKey("PlanOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PlanOption");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.PlanOption", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Plan", "Plan")
                        .WithMany("PlanOptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Subscription", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.PlanOption", "PlanOption")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProPayments.Service.Data.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("PlanOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Transaction", b =>
                {
                    b.HasOne("ProPayments.Service.Data.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("ProPayments.Service.Data.Entities.Transaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Order", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("OrderItems");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.Plan", b =>
                {
                    b.Navigation("PlanOptions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.PlanOption", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ProPayments.Service.Data.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
